### PR TITLE
Added the reference of the 'CGX' CLI to the README so people can easi…

### PR DESCRIPTION
**Pull request by jeroenouw**
### Your checklist for this pull request
🚨 Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the **fooBar branch** (left side).
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

### Description
Please describe your pull request.

❤️ Thank you!

### CODE REVIEW

**Review by race2infinity — CHANGES_REQUESTED** [review]
Thanks for the PR. This project looks very useful and promising. However, I feel like it would fall under the subcategory of "Tools" in the [Table of Contents](https://github.com/kylelobo/The-Documentation-Compendium#-table-of-contents).

Do you have any suggestions of how could I add it under "Tools"? Since "Tools" redirects to a Write The Docs link, the only way I can think of adding it under "Tools" is by adding it as a subpoint. However, I feel like that will disrupt the ToC structure.

**Comment by jeroenouw** [comment]
@kylelobo Thank you for your response, maybe an even better idea is to place it under `templates` as a subpoint called `template generator: cgx`?

**Comment by race2infinity** [comment]
Seems reasonable. Can you make the changes?

**Comment by jeroenouw** [comment]
@kylelobo I pushed the changes

**Review by race2infinity — APPROVED** [review]

**Pull request merged**
